openapi: "3.0.0"
info:
  title: Echo Service
  version: 1.0.0
paths:
  /:
    get:
      description: Echo response
      responses:
        '200':
          description: Successful response
      deprecated: false
      security: []